import { Evaluator, Parser} from './src/SimpleLangEvaluator'

console.log("\n")
console.log("Test 1")
console.log(new Evaluator().evaluate("let z: int  = 10; let y : *mut int = &mut z;"))
console.log("\n")
console.log("Test 2")
console.log(new Evaluator().evaluate("let mut x: int  = 10; let y : *mut int = &mut x; let z : *int = &x;"))
console.log("\n")
console.log("Test 3")
console.log(new Evaluator().evaluate("let mut x: int  = 10; let y : *int = &x; let z : *mut int = &mut x;"))
console.log("\n")
console.log("Test 4")
console.log(new Evaluator().evaluate("let mut x: int  = 10; let y : *mut int = &mut x; let z : *mut int = &mut x;"))
console.log("\n")
console.log("Test 5")
console.log(new Evaluator().evaluate("let mut x: int  = 10; let y : *mut int = &mut x; let z : *mut int = y; *y;"))
console.log("\n")
console.log("Test 6")
console.log((new Evaluator()).evaluate("let x : string = \"1\"; let y : *string = &x; let z : string = x;"))
console.log("\n")
console.log("Test 7")
console.log((new Evaluator()).evaluate("let mut x : string = \"1\"; let y : *mut string = &mut x; let z : string = x;"))
console.log("\n")
console.log("Test 8")
console.log(new Evaluator().evaluate("let mut x: int  = 10; {let y : *mut int = &mut x;} let z : *int = &x; *z;"))
console.log("\n")
console.log("Test 9")
console.log(new Evaluator().evaluate("let mut x: int  = 10; {let y : *int = &x;} let z : *mut int = &mut x; *z;"))
