import { Evaluator, Parser} from './src/SimpleLangEvaluator'

console.log("\n")
console.log("Test 1")
console.log(new Evaluator().evaluate("let z: int  = 10; let y : &mut int = &mut z;"))
console.log("\n")
console.log("Test 2")
console.log(new Evaluator().evaluate("let mut x: int  = 10; let y : &mut int = &mut x; let z : &int = &x;"))
console.log("\n")
console.log("Test 3")
console.log(new Evaluator().evaluate("let mut x: int  = 10; let y : &int = &x; let z : &mut int = &mut x;"))
console.log("\n")
console.log("Test 4")
console.log(new Evaluator().evaluate("let mut x: int  = 10; let y : &mut int = &mut x; let z : &mut int = &mut x;"))
console.log("\n")
console.log("Test 5")
console.log(new Evaluator().evaluate("let mut x: int  = 10; let y : &mut int = &mut x; let z : &mut int = y; *y;"))
console.log("\n")
console.log("Test 6")
console.log((new Evaluator()).evaluate("let x : string = \"1\"; let y : &string = &x; let z : string = x;"))
console.log("\n")
console.log("Test 7")
console.log((new Evaluator()).evaluate("let mut x : string = \"1\"; let y : &mut string = &mut x; let z : string = x;"))
console.log("\n")
console.log("Test 8")
console.log(new Evaluator().evaluate("let mut x: int  = 10; {let y : &mut int = &mut x;} let z : &int = &x; *z;"))
console.log("\n")
console.log("Test 9")
console.log(new Evaluator().evaluate("let mut x: int  = 10; {let y : &int = &x;} let z : &mut int = &mut x; *z;"))
console.log("\n")
console.log("Test 10")
console.log(new Evaluator().evaluate("let foo = |x : int| -> int {return x+2;}; let mut y : int = 10; foo(y); y;"))
console.log("\n")
console.log("Test 11")
console.log(new Evaluator().evaluate(`let foo = |x : &mut string| -> &mut string {*x; return x;}; let mut y : string = "hello"; foo(&mut y);`))
console.log("\n")
console.log("Test 12")
console.log(new Evaluator().evaluate(`let foo = |x : &mut string| -> &mut string {*x; return x;}; let mut y : string = "hello"; let z : &mut string = &mut y; foo(&y);`))
console.log("\n")
console.log("Test 13")
console.log(new Evaluator().evaluate(`let foo = | | -> &mut string {let z : &mut string = &mut y; return z;}; let mut y : string = "hello"; let x : &mut string = &mut y; foo();`))
console.log("\n")
console.log("Test 14")
console.log(new Evaluator().evaluate(`let foo = | | -> &mut string {let z : &mut string = &mut y; return z;}; let mut y : string = "hello"; let x : &mut string = &mut y;`))
console.log("\n")
console.log("Test 15")
console.log(new Evaluator().evaluate("let mut x: int  = 10; {let y : &mut int = &mut x;} *y;"))
